//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco.Datos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NODO-1\\NODO1;Initial Catalog=SISTEMA_BANCARIO;Persist Security Info=T" +
            "rue;User ID=sa;Password=C3$4r2003")]
        public string SISTEMA_BANCARIOConnectionString {
            get {
                return ((string)(this["SISTEMA_BANCARIOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=nodo-2\\nodo2;Initial Catalog=SISTEMA_BANCARIO;Persist Security Info=T" +
            "rue;User ID=sa;Password=C3$4r2003")]
        public string SISTEMA_BANCARIOConnectionString1 {
            get {
                return ((string)(this["SISTEMA_BANCARIOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=nodo-3\\nodo3;Initial Catalog=SISTEMA_BANCARIO;Persist Security Info=T" +
            "rue;User ID=sa;Password=C3$4r2003")]
        public string SISTEMA_BANCARIOConnectionString2 {
            get {
                return ((string)(this["SISTEMA_BANCARIOConnectionString2"]));
            }
        }
    }
}
